### ISSUE TITLE
`dsy_board_gen.py` Problems with Python 3.8.10 

### ISSUE THREAD

**Issue by CorvusPrudens** [electro-smith/pd2dsy#16]
For some reason, the `filter_map_ctrl` function throws an exception when using python 3.8.10, which is the version shipped with my release of Ubuntu at the moment:

~~~
Traceback (most recent call last):
  File "daisy_board_gen.py", line 161, in <module>
    template_code = generate_target_struct(infile)
  File "daisy_board_gen.py", line 122, in generate_target_struct
    replacements['init_single'] = filter_map_ctrl(components, 'typename', 'daisy::AnalogControl', 'init_single')
  File "daisy_board_gen.py", line 51, in filter_map_ctrl
    return "\n\t\t".join(map(lambda x: x[init_key].format_map(x), set))
  File "daisy_board_gen.py", line 50, in <lambda>
    set = map(lambda x, i: x | {'i': i}, set, range(1000))
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
~~~

Oddly enough, doing a pointless list comprehension before the second line in the function fixes the issue (`[x for x in set]`). Maybe it's a bug in how python used to handle filter objects?

Anyway, this is all not very relevant since the latest python release is 3.10. I'm just putting this here in case this issue crops up in the future.

**Comment by stephenhensley** [comment]
this is/has been moved outside of the scope of this repo
